### ISSUE TITLE
Refactor collection tree

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#147] opened 2018-10-27 12:38 UTC
* [x] Drop 'My Library' heading
* [x] Use 'My Library' root folder instead of 'All Documents' node on desktops
* [x] Use group library root folders instead of 'All Documents nodes on desktops
* [x] Use 'All Items' node to show all documents on mobiles / touch devices
* [x] Replace '/' with 'Library' (referring to 'Web Library') or 'Libraries' ('My Library' + Group Libraries) in touch header
* [x] Handle initial transitions by adding a global spinner
* [x] Bring back `icon-folders` for collections with subcollections on mobiles and touch devices
* [x] Replace dummy touch header in sidebar with working version (for tablets and large touch devices)
* [x] Tweak 'desktop header'
* [x] Fix last level
* [x] Investigate missing folder icons [remark: cannot reproduce anymore]
* [x] Fix open / selected logic on mobiles / touch devices with viewports larger than 480px
* [x] Style 'new collection' item
* [x] Tweak tree layout
* [x] ~~Add 'add collection' option to root folders (libraries) on mobiles / touch devices~~
* [x] Show plus icon in collapsed library roots
* [x] Style options dropdown
* [x] Keyboard navigation
* [ ] Use double click and right/left arrow keys to open/close a collection on desktops
* [x] Use 'click to edit' (select-delay-click) to rename collections on desktops
* [x] Implement _Rename_ using a modal on touch devices

**Comment by tnajdek** [comment] 2018-10-29 10:01
What should be the default view on mobiles? Most obvious answer would be the root of the tree, i.e. the list of libraries, however I have a feeling that it would be more useful if we would show the contents of "My Library"?

**Comment by flachware** [comment] 2018-10-29 16:57
@tnajdek please have a look at the discussion between @dstillman and me on IRC regarding that topic. We concluded that showing the content of 'My Library' by default on mobiles would be cumbersome for users with lots of collections who want to reach the group library quickly.

So the default view on mobiles should be:
```
Icon + My Library (root)
--- white gap ---
Heading: Group Libraries
Icon + Group Library 1 (root)
Icon + Group Library 2 (root)
…
```

**Comment by flachware** [comment] 2018-11-03 15:18
@tnajdek when the web library is loaded on mobiles or touch devices, there is a transition visible in the collection tree. I guess this is happening because the `open` and `selected` classes are not set initially but a bit later?

How does the loading procedure of the collections work? Is it possible to just show the collections on principle or do we need to add a spinner anyway (sometimes it looks like the set of collections is updated during the loading process)? Or would a global spinner be helpful when the web library is still loading data initially?

In case you think the initial loading is fine for now, we could think of kind of a global class that disables/enables css transitions, so we could enable the level transitions when everything is really ready.

**Comment by flachware** [comment] 2018-11-03 15:30
@tnajdek for some reason we lost the `icon-folders` icon (28px) for collections that contain subcollections (so basically collections that would have a twisty on desktops) on mobiles and touch devices. Could you have a look at that?

**Comment by flachware** [comment] 2018-11-03 16:44
@tnajdek re 'fix last level': I believe there is something wrong with the last level, that’s why the sidebar is empty on large touch devices. If I’m not mistaken collections that should be the last level (and thus get `.level-last`) have an empty 'last' level inside?

**Comment by flachware** [comment] 2018-11-04 14:33
@tnajdek sometimes folder icons are missing, having a look at the DOM in the dev tools shows that the `<use>` element is empty in those cases. Any ideas why this could happen?

![screenshot 2018-11-04 at 15 30 31](https://user-images.githubusercontent.com/419747/47965391-f9ea1400-e046-11e8-9382-aa330544f3e5.png)

**Comment by flachware** [comment] 2018-11-04 14:48
@tnajdek re todo 'Fix open/selected logic on mobiles / touch devices with viewports larger than 480px': the open / selected logic seems to be fine on 480px and smaller screens, but above that these classes and the aria-expanded property are not set accordingly, which leads to two visible levels at the same time.

![screenshot 2018-11-04 at 15 45 53](https://user-images.githubusercontent.com/419747/47965545-efc91500-e048-11e8-8c79-f85f2f710afc.png)

**Comment by flachware** [comment] 2018-11-06 08:05
@tnajdek a suggestion re 'global spinner': the mobile collection tree has transition with a duration of 0.6s, a duration we would have to wait before we can remove the global spinner, which is a bit pointless.

How about adding a `.no-transition` class to the library root which lets me disable all transitions while the global spinner is visible? Once you remove the global spinner you would also remove that class (and thus re-enable transitions). Does that make sense to you?

**Comment by tnajdek** [comment] 2018-11-06 13:56
@flachware I've added a `.no-transition` class on `.library-container` during the initial load, will that work?

**Comment by flachware** [comment] 2018-11-07 08:18
@tnajdek should be working now. Except for the transition in the touch header, I guess this is a timing issue and you have to wait for the touch header to be ready before you remove the class?

**Comment by tnajdek** [comment] 2018-11-08 16:08
Race condition should be resolved now and I've added a global spinner (please feel free to adjust as needed).

Do you still see missing folder icons? I've seen that before but wasn't able to reproduce for a while.

**Comment by tnajdek** [comment] 2018-11-08 16:19
> Show plus icon in collapsed library roots

If it's a group library and it has not been opened yet, it will need to load first. Pressing plus button renders a "virtual" entry where user can enter new collection name. If we allow to do that while library is closed we need to choose how to handle this. I can think of a couple of options:

1. Show spinner next to the library name. Once it loads, open and focus on the "virtual" entry. To be more consistent we could always show spinner when opening library that has not loaded yet
1. Open library and create virtual entry while collections download in the background. User can immediately enter collection name, however interface will get unstable as collections pour in. This can be frustrating for the end user.

@flachware what are your thoughts on this?

**Comment by flachware** [comment] 2018-11-08 19:55
@tnajdek the race condition looks good to me now.

Do we need/want the global spinner only in the xs size? Also, when I do a hard reload it strikes me that I see a blank page most of the loading time, then briefly the spinner and then the full interface. Would there be a way to insert the global spinner earlier?

I haven’t seen the missing icons lately, so that’s maybe gone – but it’s good to know that you have seen them too.

**Comment by flachware** [comment] 2018-11-08 21:19
@tnajdek re plus icon and group libraries: I think variant 1 is the way to go. If there wouldn’t have been any concrete ramifications of the current loading behavior I would have said let’s keep that for later. But the plus icon is actually a good example that we should do the loading (and its feedback) in a structured way.

So, if you open a group library or hit its plus icon a spinner should appear to the right until the items are loaded. Now that we are already look into this, shouldn’t we also add a spinner in the empty (still loading) level on touch devices?

**Comment by flachware** [comment] 2018-11-11 16:36
@tnajdek when you open the options menu in the collection tree on desktops, the menu just doesn’t appear but looks like as if it would slide in from the right side. This only happens for me when I toggle the menu twice at least, it does not happen the first time. Can you reproduce that? I think this is the glitch that I have seen in ZBib once, but we could not reproduce it.

**Comment by flachware** [comment] 2018-11-11 16:43
@tnajdek when I select a collection it takes some time until the selection gets highlighted. I guess this is because we have to fetch the tags, items, and so on. To me it looks like we are fetching the items in two steps, like first we just know the number and then the actual data gets fetched. Would you mind to elaborate a bit on the loading process? Would there be a way to immediately select a collection and handle the loading in the asynchronous parts?

**Comment by tnajdek** [comment] 2018-11-12 10:40
> @tnajdek when I select a collection it takes some time until the selection gets highlighted. I guess this is because we have to fetch the tags, items, and so on. 

That's not the case, most of this time is spent in react rendering changes. I'm aware of performance issues, I've opened an issue (#153) to keep track of that.

Also if you have a look at production mode (`npm run build` followed by `npm run serve`), you will notice performance is substantially better.

**Comment by tnajdek** [comment] 2018-11-12 13:29
@flachware added spinner when opening group libraries on desktop.

> So, if you open a group library or hit its plus icon a spinner should appear to the right until the items are loaded. Now that we are already look into this, shouldn’t we also add a spinner in the empty (still loading) level on touch devices?

First of all it's worth noting that the only case where this can happen is when you open a group library for the first time, so it's a relatively rare case. Also what sort of spinner would it be? A small spinner immediately after user clicks on the library prior to sliding animation? Or a larger spinner to avoid showing empty list while collections are being fetched? I believe the latter would not work very well, because the sliding animation takes about as long as it takes to fetch a small group library (and it happens async), would you be OK with the former?

**Comment by flachware** [comment] 2018-11-13 09:06
@tnajdek I tried to have a look at the production version but ended up with a blank page (the static index.html), am I missing something?

**Comment by tnajdek** [comment] 2018-11-20 11:49
@flachware Adding subcollections on touch devices is currently broken. Is the plan to have that option accessible via "..." menu as it is currently? Bear in mind that will trigger animation first to render "virtual" item. I was wondering if instead we shouldn't have a button in the touch header to trigger adding (sub)collection inside currently visible library/collection.

**Comment by flachware** [comment] 2018-11-21 20:51
@tnajdek after giving your question some thought I agree, we should put the _New Subcollection_ option in the (still missing) '...' menu in the touch header only. I believe the UI would look odd otherwise.

However, I tend to say that some options have to work differently on touch devices than on desktops. I’m questioning the 'in-place' editing here – shouldn’t we put options like _Rename_, _New Subcollection_, _Move_ (I guess we will have that at some point?) into a modal? Let’s discuss this a bit more, but I think that would be closer to our default mode / edit mode metaphor, and we won’t be able to realize the _Move_ option without a modal anyway.

**Comment by flachware** [comment] 2018-11-23 19:09
@tnajdek what about _Delete_? Would you also just put it in the touch header and apply it to the currently selected collection?

I do think we have a plan otherwise, I’m just not sure if we really should drop the '...' next to each item, keeping _Rename_ and _Delete_ should work fine there and would add some comfort for the users.

**Comment by flachware** [comment] 2018-11-29 20:12
@tnajdek in order to make the keyboard navigation work on touch devices we have to ensure that the `tabindex` attribute is only set in the currently visible level, otherwise tabbing through the collections of a level causes a jump to the nested collections of the next level once you reach a collection with subcollections. Mind to have a look?

**Comment by flachware** [comment] 2018-11-29 20:38
@tnajdek the editable component looks good to me! Minor (?) detail: the text in the editable is not auto-selected like in the metadata-list, also hitting ESC does not clear selected text after closing the editable. Why do we differ here?

**Comment by tnajdek** [comment] 2018-11-29 21:42
@flachware I've tweaked the editable in collection tree it will now

* Select text on focus when renaming collections
* ESC cancels editing reverting to the original value (or cancels if adding a new collection)
* ENTER/TAB confirms, triggers update

**Comment by flachware** [comment] 2018-12-04 19:55
@tnajdek looks good to me, except for TAB after 'renaming' with no change, then the active editable stays open for some reason.

**Comment by flachware** [comment] 2019-02-04 14:37
@dstillman might want to chime in here; as far as I remember the idea was to reflect the future client, which would have click-delay-click to rename (the default on macOS) and double click to open/close the collection.

**Comment by tnajdek** [comment] 2019-04-01 14:37
I've split off the issue of double clicking into #200, which we can discuss & address separately (probably post 1.0), hence closing this issue.

**Closed by tnajdek** 2019-04-01 14:37 UTC
