### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#230] opened 2019-05-22 17:51 UTC
Search on phones:
- [x] Wire navbar search-toggle button
- [x] Insert searchbar only in touch-header for phones
- [x] Replace dummy input with real search field
- [x] Hook up Cancel button
- [x] Fade in/out searchbar (react-transition-group)
- [x] Set/unset .search-active class
- [x] 'Search Results' transitions in touch-nav
- [x] Tap on .search-backdrop should cancel search mode
- [x] Hide .search-toggle in .view-libraries-active state

General:
- [x] Keyboard navigation (also see #218)

Wireframes for the search functionality on desktops/tablets and phones:

<img width="1440" alt="search-desktop@2x" src="https://user-images.githubusercontent.com/419747/58196486-b4332700-7cca-11e9-88f7-c85a5268112f.png">

<img width="320" alt="search-phone-1@2x" src="https://user-images.githubusercontent.com/419747/58196504-bb5a3500-7cca-11e9-94d8-e8abd8d2ce90.png">

<img width="320" alt="search-phone-2@2x" src="https://user-images.githubusercontent.com/419747/58196516-c1e8ac80-7cca-11e9-85cf-0476f887d4ea.png">

<img width="320" alt="search-phone-3@2x" src="https://user-images.githubusercontent.com/419747/58196522-c4e39d00-7cca-11e9-966c-79e55dd7227b.png">

<img width="320" alt="search-phone-4@2x" src="https://user-images.githubusercontent.com/419747/58196530-c7de8d80-7cca-11e9-9387-359bc9e6e5e7.png">

**Comment by flachware** [comment] 2019-05-23 14:11
@tnajdek I added a dropdown button and a clear button to the search box. Could you add the actual dropdown for the 'Title, Creator, Year' and Everything' options (what about 'All Fields and Tags'?)?

The clear button should only be inserted when the search input isn’t empty (and it needs to be wired).

**Comment by flachware** [comment] 2019-05-30 07:11
@tnajdek I think I just realized how the positioning of the dropdown menu really works; So it takes the first positioned parent (offset parent) and translates the menu to the right position. With that approach the menu can even escape scrolling elements in case the offset parent is outside. In that light the dropdown component looks more flexible than I thought.

**Comment by flachware** [comment] 2019-05-30 07:28
@tnajdek to get us started I prepared dummy elements for the search on phones. Please have a look at the to-do list in the first issue comment and I’ll try to explain the last three tasks in more detail here:

- Once the search-toggle has been tapped, fade in the searchbar with the help of react-transition-group.

- Likewise, when the search-toggle has been tapped, set `.search-active` class on `.library-container`. With the help of this class I should be able to fade in the empty `.items` section in case it is not visible and add opacity. In case `.items` is visible (`.view-item-list-active` already set) I would soften the text of its items. Remove `.search-active` once results are rendered.

- Once a search result is selected, fade out searchbar and `Search Results` should (simultaneously) move from the center to the left of the touch-nav. Going back with `Search Results` should move it back to the center of the touch-nav and fade in the searchbar.

I’ll try to add corresponding styles asap, so we can see the search results.

**Comment by flachware** [comment] 2019-05-31 22:00
@tnajdek I realized that we will need to do all the fading (`.searchbar` and `.items`) by setting the fade classes we already have (otherwise I could not distinguish the end of searching and moving back from items to the collection tree – these two cases should look different).

You still need to set the `search-active` class, this translates `items` into the viewport. The `.items` element has to be cleared (has to be empty) in case it is not active currently. When canceling the search mode we have to fade out `.items` first, then remove the `search-active` class (otherwise the fade out would be off screen).

**Comment by flachware** [comment] 2019-06-03 19:35
@tnajdek the searchbar looks pretty good already! I think there are a few tweaks left to get the items-list right:

- Using a fade in/out react-transition-group for `.items` should prevent the slide in/out transitions.

- Once there are search results, we either have to remove `.search-active` or set another class, e.g. `.search-results` to reset the softened text. I guess the latter makes more sense.

- When you are in the items-list view before you start searching, I would like to avoid a blank view when you activate the searchbar, could we keep the items in the list until a query is entered?

- Show correct content in the list while fading out when canceling search (either empty, search results, or items)

**Comment by flachware** [comment] 2019-06-03 19:50
@tnajdek just in case you are not aware of, the searchbar still gets inserted into all touch-headers instead of just into the one for phones.

**Comment by flachware** [comment] 2019-06-03 21:39
@tnajdek I guess it would make sense to focus the search-input on phones when you hit the clear button?

**Comment by tnajdek** [comment] 2019-06-04 11:05
> @tnajdek I guess it would make sense to focus the search-input on phones when you hit the clear button?

Any reason not to do it on other devices as well?

**Comment by flachware** [comment] 2019-06-04 12:17
@tnajdek well phones are the only devices where we know for sure that the user wants to continue searching when the clear button is hit (otherwise it would be the cancel button). But on second thought it doesn’t hurt on other devices either (and it would be in line with the client), so let’s focus the input on all devices.

**Comment by tnajdek** [comment] 2019-06-04 15:56
@flachware I've implemented multiple tweaks & fixes, we should now be pretty much there. Could you please give it a go and let me know if you can spot anything not working as expected?

**Comment by flachware** [comment] 2019-06-04 16:36
@tnajdek I’ve also added some tweaks that should work within the current logic (just spotted an issue, I’ll write a separate comment in a moment). I thought softening didn’t work so well after all so I switched to a black 'backdrop'.

So there is one issue that is very noticeable: when you are in the collection-tree and start searching, enter a query and then hit the clear button, you see the item list instead of the collection-tree. So we have to clear the items-list and remove the `view-item-list-active` class in this case.

When you are in the collection-tree and cancel search, the items-list doesn’t fade out but is removed immediately – I guess this happens because the removal of the `.search-active` class doesn’t wait for the (react-transition-group) fade out of the items-list yet (or there is no fade out at all).

**Comment by flachware** [comment] 2019-06-04 16:56
@tnajdek ok, to solve the issue I’ve added a .search-backdrop as a real element. Currently it is permanently in there, so what has to be done:

It should fade in with react-transition-group when a) the user is already in the items-list view and b) .search-active is true. It will cover the items so you can’t tap on them anymore.

It should fade out when .search-results get set.

It should fade out when you are in the items-list view and cancel search.

**Comment by flachware** [comment] 2019-06-05 14:49
@tnajdek I had a look at the search in the item-details view: I think as it works currently we should stay at `.view-item-details-active.search-active`, the backdrop will cover the item-details view. Once there are results we switch to `.view-items-list-active.search-results` and have to react-transition-group fade out the backdrop. Can you do that?

**Comment by flachware** [comment] 2019-06-10 19:56
@tnajdek in order to refactor the search transitions systematically I started with the states of the library view (starting search in other views won’t work currently).

So basically we have three views to start search – library view, items list view, and item details view. Search transitions have to work differently depending on the view you start. And these are the states I’m working with:

Library view states:
- Init
- Search results
- Item details
- Cancel library view (before results)
- Cancel items list

I recognized three hickups in the current behavior (just talking about search that has been started in the library view):
- [ ] Canceling search before entering a query shows item list items in the fade out
- [ ] Clearing the search field after a query has been entered should switch to `.view-library-active` and clear item list
- [ ] When canceling search in the item list there should not be any translations in the touch-header nav 
- [ ] Currently I have no way to differentiate wether you cancelled search in the library view before results are shown or in the items list (search results). Could We keep the `.search-active` and `.search-results` (mutex) while we set the `.search-cancel` class? This way I would know in which state the search has been cancelled.

Could you please have a look into these issues?

**Comment by tnajdek** [comment] 2019-06-11 12:53
> When canceling search in the item list there should not be any translations in the touch-header nav

Animation in touchheader is caused by the fact that view is changed from **item-list** (showing search results) to **library** view. Changes in the touch header need to happen at this point to reflect the new state. The only way to hide this I can think of is to disable these transitions in touch header, via css, based on some global class (`.search-cancel`?). Also I think this visual issue is quite minimal and we could live with it for 1.0.

**Comment by flachware** [comment] 2019-06-12 17:12
@tnajdek you are totally right, I’m responsible for that transition. Thanks for the `.search-cancel` tip, that did the trick.

**Comment by tnajdek** [comment] 2019-06-20 16:59
@flachware I think we can close this issue? (keyboard navigation is tracked in #218)

**Comment by flachware** [comment] 2019-07-01 13:39
@tnajdek there are some tweaks needed for searching on sm screens:

- [ ] Could you remove the .search-init class on sm screens the same way as on phones?

- [ ] When clearing a search on sm screens, could you set/unset the .search-cancel class the same way you do on phones on 'Cancel'?

**Comment by tnajdek** [comment] 2019-07-01 17:23
@flachware please have a look if that's what you had in mind

**Comment by flachware** [comment] 2019-07-01 17:51
@tnajdek yes that looks good to me, now I should be able to fix the last transitions.

**Comment by flachware** [comment] 2019-07-09 13:58
@tnajdek I believe the search behaves differently on sm devices and phones: on phones, when I start searching in item-details, get a list of search results, and then clear the search I’m back in the item-details (`.view-item-details-active`) – but on sm devices you would end up in the item-list (`.view-item-list-active`). Could you have a look at this?

**Comment by tnajdek** [comment] 2019-07-12 15:49
@flachware I've implemented a tweak so that once you empty search input on multi column devices (where we don't have explicit search mode) it goes back to the item where you've started. I'm actually not sure this is correct behaviour, also it triggers animation. Let me know what you think

**Comment by flachware** [comment] 2019-07-15 15:23
@tnajdek the behavior looks good to me in general, I’ll take care of the transitions. But I have two more requests:

Could we keep the `.search-init` class while `.search-cancel` is set?

And it seems as if the classes on the `.library-container` are not set at the same time. E.g. on a sm device when you start searching in the item-details view then you are in the item-list view and get the classes `.view-item-list-active.search-results`, when you change them in the dev tools to `.view-item-details-active.search-results.search-cancel` then you should see the item-details fading in. The same should happen when you clear the search box, but it does not. I can’t be sure but I believe there is a state in between where only the `.view-item-details-active` class is set without `.search-results.search-cancel` is set and thus the transitions get messed up. Could you ensure that those classes are set at the same time?

**Comment by tnajdek** [comment] 2019-07-16 11:24
@flachware I think I fixed these, please let me know if I got it right

**Closed** 2019-07-19 13:11 UTC
